# Generated by Django 3.1.1 on 2020-09-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0003_auto_20200905_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='following',
        ),
        migrations.AddField(
            model_name='relationship',
            name='relationship_status',
            field=models.BooleanField(default=True),
        ),
    ]
